#!/usr/bin/env python3
"""
Verify BEP44 signatures generated by SeedSigner.

This tool helps verify that the signatures produced by SeedSigner are valid
and can be used in actual DHT PUT requests.

Usage:
    python3 tools/verify_bep44_signature.py

You'll be prompted to enter the signature data from the QR code that SeedSigner
displays after signing.
"""

import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from seedsigner.helpers.ed25519_utils import verify_bep44_signature, get_bep44_storage_target
from seedsigner.helpers.bep44_cbor import decode_bep44_result
from urtypes.bytes import Bytes
import json


def verify_from_hex_input():
    """Verify signature from manual hex input."""
    print("\n" + "="*60)
    print("Manual Signature Verification")
    print("="*60)

    try:
        public_key_hex = input("\nEnter public key (64 hex chars): ").strip()
        signature_hex = input("Enter signature (128 hex chars): ").strip()
        seq = int(input("Enter sequence number: ").strip())
        value_hex = input("Enter value (hex): ").strip()
        salt_hex = input("Enter salt (hex, or press Enter for none): ").strip()

        # Convert from hex
        public_key = bytes.fromhex(public_key_hex)
        signature = bytes.fromhex(signature_hex)
        value = bytes.fromhex(value_hex)
        salt = bytes.fromhex(salt_hex) if salt_hex else None

        # Validate lengths
        if len(public_key) != 32:
            print(f"❌ Error: Public key must be 32 bytes, got {len(public_key)}")
            return False

        if len(signature) != 64:
            print(f"❌ Error: Signature must be 64 bytes, got {len(signature)}")
            return False

        # Verify signature
        print("\n--- Verifying Signature ---")
        is_valid = verify_bep44_signature(public_key, seq, value, signature, salt)

        if is_valid:
            print("✅ Signature is VALID!")

            # Calculate storage target
            target = get_bep44_storage_target(public_key, salt)
            print(f"\nDHT Storage Target: {target.hex()}")

            # Display DHT PUT message format
            print("\n--- DHT PUT Message Format ---")
            dht_message = {
                "k": public_key_hex,
                "sig": signature_hex,
                "seq": seq,
                "v": value_hex
            }
            if salt:
                dht_message["salt"] = salt_hex

            print(json.dumps(dht_message, indent=2))

        else:
            print("❌ Signature is INVALID!")

        return is_valid

    except ValueError as e:
        print(f"❌ Error: Invalid input - {e}")
        return False
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return False


def verify_from_ur_string():
    """Verify signature from UR string (scanned QR result)."""
    print("\n" + "="*60)
    print("Verify from UR:BYTES String")
    print("="*60)
    print("\nPaste the UR:BYTES string from SeedSigner's result QR:")
    print("(Should look like: ur:bytes/...)")

    ur_string = input("\nUR String: ").strip()

    try:
        # Parse UR string
        if not ur_string.lower().startswith("ur:bytes/"):
            print("❌ Error: UR string must start with 'ur:bytes/'")
            return False

        # For single-frame QRs, extract the CBOR data
        # This is simplified - for multi-frame, you'd need URDecoder
        # Extract base32-ish encoded data after ur:bytes/
        encoded_part = ur_string[9:]  # Skip "ur:bytes/"

        print("\n⚠️  Note: Multi-frame UR decoding not implemented in this tool.")
        print("For multi-frame results, use the QR scanner to collect all frames,")
        print("then extract the hex values manually from SeedSigner's display.")

        return False

    except Exception as e:
        print(f"❌ Error parsing UR string: {e}")
        return False


def verify_test_vector():
    """Verify with a known test vector."""
    print("\n" + "="*60)
    print("Test Vector Verification")
    print("="*60)

    # This is a deterministic test - if you have a known seed, derive expected results
    print("\nThis would verify against a known test vector.")
    print("For actual testing, use manual input from SeedSigner's output.")

    # Example test case (you would need to generate this with known seed)
    print("\n⚠️  Test vector verification not yet implemented.")
    print("Use manual hex input mode to verify SeedSigner signatures.")

    return False


def display_menu():
    """Display verification options menu."""
    print("""
╔══════════════════════════════════════════════════════════════╗
║         BEP44 Signature Verification Tool                   ║
║                                                              ║
║  Verify ed25519 signatures generated by SeedSigner          ║
╚══════════════════════════════════════════════════════════════╝

Options:
  1. Verify from hex input (recommended)
  2. Verify from UR:BYTES string (not yet implemented)
  3. Verify test vector (not yet implemented)
  4. Exit

    """)

    choice = input("Select option (1-4): ").strip()
    return choice


def main():
    """Main verification loop."""
    while True:
        choice = display_menu()

        if choice == "1":
            verify_from_hex_input()
            input("\nPress Enter to continue...")

        elif choice == "2":
            verify_from_ur_string()
            input("\nPress Enter to continue...")

        elif choice == "3":
            verify_test_vector()
            input("\nPress Enter to continue...")

        elif choice == "4":
            print("\nGoodbye!\n")
            break

        else:
            print("\n❌ Invalid choice. Please select 1-4.")
            input("Press Enter to continue...")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nInterrupted by user. Goodbye!\n")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
